### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Wolfyxon** [Wolfyxon/GodotTogether#1]
# Non-urgent todo
- [ ] Clean up and reorganize the code
  - [x] Split and rewrite changeDetector
      - [x] file_sync
      - [x] node_sync 
  - [ ] Reorganize RPC functions 
  - [ ] Prefix RPC functions with `s2c` and `c2s` to better distinguish the communication
- [ ] Improve performance

# Version milestones
## 1.0 alpha
- [x] Fix critical bugs
  - [x] Godot sometimes crashing when joining a project
  - [ ] Sometimes crashing when reloading a scene (testing shows it's caused by node sync logic)
  - [x] Peers bouncing back changes 
  - [x] 3D Rotation being weird (started happening after prev bug got fixed)
- [x] Node sync
  - [x] Properties 
    - [x] Local change detection
    - [x] Syncing changes of open scenes between users
    - [x] Resource sync
    - [ ] Properties that require functions
       - [ ] Label
          - [x] font size override
          - [ ] styles
          - [ ] fonts
          - [ ] colors
          - [ ] constants
        - [ ] Panel
          - [ ] styles
        - [ ] Button
          - [ ] styles  
  - [x] Adding
  - [x] Reparenting
  - [x] Reordering 
  - [x] Removing
  - [x] Renaming
- [x] Project files download
  - [x] Calculating hashes for every file in the project
  - [x] Comparing file hashes between user and server upon join
  - [x] Server sends files that don't match the server side checksum for the client to download
- [x] Basic security
  - [x] Password protection
  - [x] Checking and allowing or rejecting remote IP addresses (outside of the local network) 
  - [x] Path validation to prevent access to files outside of the project
- [x] Real time file sync
  - [x] Replicating changes even when a scene isn't open / file sync
   - [x] Reload scenes when joining
- [x] Better security
  - [x] User permissions
  - [x] Approving users before they join
  - [x] Warn users when a tool script is detected
- [x] Better GUI
- [x] Plugin update checking and installing

## 1.1 Alpha
- [x] Fix bugs
  - [x] Shared non-file resources becoming independent 
  - [x] Changes sometimes not replicating from clients to server
    - [x] Node property changing
    - [x] Node adding
    - [x] Node deleting
- [x] Support more sync
  - [x] Reordering
  - [x] Adding with properties (pasting, custom classes)
- [ ] Automatic file reload without the annoying popup (hopefully possible)
- [ ] Further improve UX
- [ ] Better tool script warning
